### ISSUE TITLE
Instructions incorrectes pour générer de nouvelles maps

### ISSUE THREAD

**Issue by HeavyTony2** [Mr-Donot/QueensGame#5]
https://github.com/Mr-Donot/QueensGame/blob/40f2aa04a44572ad7dac82459564849e9774a57c/README.md?plain=1#L23
La constante citée n'est même pas présente dans le fichier. Il y a cependant NB_TRY_TO_GENERATE. J'ai beau modifier les paramètres, aucun changement n'est enregistré dans maps.json. La commande semble tourner dans le vide.

**Comment by FlorianDaunay** [comment]
Bonjour, le readme est de nouveau à jour, cela devrait éclaircir ce souci :)
